export const ActionTypes = {
    GET_EMPLOYEES: "GET_EMPLOYEES",
    ADD_EMPLOYEES: "ADD_EMPLOYEES",
    EDIT_EMPLOYEES: "EDIT_EMPLOYEES",
    UPDATE_EMPLOYEES: "UPDATE_EMPLOYEES",
    DELETE_EMPLOYEES: "DELETE_EMPLOYEES",
    TOGGLE_MODAL: "TOGGLE_MODAL",
    MODAL_EDIT: "MODAL_EDIT",
}