export const ActionTypes = {
    GET_EMPLOYEES: "GET_EMPLOYEES",
    ADD_EMPLOYEES: "ADD_EMPLOYEES",
    EDIT_EMPLOYEES: "EDIT_EMPLOYEES",
    DELETE_EMPLOYEES: "DELETE_EMPLOYEES",
    TOGGLE_MODAL: "TOGGLE_MODAL"
}